name: Build Resume

on:
  push:
    paths:
      - resume.tex

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert LaTeX to HTML
        run: pandoc -s resume.tex --template web/template.html -o web/resume.html

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add web/resume.html
          git commit -m "Update resume.html via GitHub Actions" || echo "No changes to commit"
          git push
